---
- name: Install_Packages_and_Start_Nginx
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Install_Packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Starte_Nginx_Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
