---
- name: Hardening_SSH
  hosts: linux
  become: true

  tasks:
    - name: Change_SSH_Port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Port"
        line: "Port {{ ssh_port }}"
        state: present

    - name: Desactivate_Root_Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Reload_SSH_Service

  handlers:
    - name: Reload_SSH_Service
      ansible.builtin.service:
        name: ssh
        state: restarted
