---
- name: Hardening_SSH
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Prompt_for_SSH_Port
      ansible.builtin.pause:
        prompt: "Quel port SSH souhaitez-vous utiliser ? Par d√©faut : {{ ssh_port }}"
      register: ssh_port_input

    - name: Change_SSH_Port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Port"
        line: "Port {{ ssh_port }}"
        state: present

    - name: Desactivate_Root_Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
      notify: Reload_SSH_Service

  handlers:
    - name: Reload_SSH_Service
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: ssh
        state: restarted
        enabled: true
